services:
	mssql:
		image: mcr.microsoft.com/mssql/server:2022-latest
		container_name: mssql
		environment:
			- ACCEPT_EULA=Y
			- MSSQL_SA_PASSWORD=YourStrong!Passw0rd
			- MSSQL_PID=Developer
		ports:
			- "1433:1433"
		volumes:
			- mssql_data:/var/opt/mssql
		networks:
			- fasttodo-network
