services:
  db:
    image: postgres:17.5
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:5.3.0
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
