services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql
    restart: always
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: MyPass@word
    ports:
        - 1433:1433
    volumes:
        - mssql_data:/var/opt/mssql
    networks:
        - fasttodo-network
    healthcheck:
        test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "MyPass@word", "-C", "-Q", "SELECT 1"]
        interval: 5s
        timeout: 5s
        retries: 10

  migrator:
    container_name: fasttodo-migrator
    build:
        context: ../
        dockerfile: Dockerfile.Migrations
    environment:
        DB_CONNECTION_STRING: Server=db,1433;Database=FastTodo;User ID=SA;Password=MyPass@word;Encrypt=True;TrustServerCertificate=true
        PROJECT: ./Persistence/EF/FastTodo.Persistence.EF.csproj
        CONTEXT: FastTodoSQLDbContext
        SqlProvider: SQLServer
    depends_on:
        db:
          condition: service_healthy
    networks:
        - fasttodo-network
    restart: "no"

  api:
    container_name: fasttodo-api
    build:
      context: ../src
      dockerfile: Dockerfile.dev
    ports:
        - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SQLServer=Server=db,1433;Database=FastTodo;User ID=SA;Password=MyPass@word;Encrypt=True;TrustServerCertificate=true
      - SqlProvider=SQLServer
    restart: always
    depends_on:
      db:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    networks:
        - fasttodo-network

volumes:
  mssql_data:

networks:
  fasttodo-network:
