services:
   db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: mssql
      restart: on-failure
      environment:
         ACCEPT_EULA: Y
         MSSQL_SA_PASSWORD: MyPass@word
         MSSQL_PID: Developer
      ports:
         - 1433:1433
      volumes:
         - mssql_data:/var/opt/mssql
      networks:
         - fasttodo-network

   api:
      container_name: fasttodo-api
      build:
      context: ../src
      dockerfile: Dockerfile.dev
      ports:
         - "5001:5001"
      environment:
         - ASPNETCORE_ENVIRONMENT=Development
      restart: on-failure
      depends_on:
         - db
      networks:
         - fasttodo-network

volumes:
   mssql_data:
