services:
   db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: mssql
      restart: always
      environment:
         ACCEPT_EULA: Y
         MSSQL_SA_PASSWORD: MyPass@word
         MSSQL_PID: Developer
      ports:
         - 1433:1433
      volumes:
         - mssql_data:/var/opt/mssql
      networks:
         - fasttodo-network

volumes:
   mssql_data:
