services:
  db:
    image: postgres:17.5
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pg-network

  adminer:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: catsarecool
    ports:
      - 5050:80
    networks:
      - pg-network

volumes:
  pgdata:

networks:
  pg-network:
