services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql
    restart: always
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: MyPass@word
    ports:
        - 1433:1433
    volumes:
        - mssql_data:/var/opt/mssql
    networks:
        - fasttodo-network
    healthcheck:
        test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "MyPass@word", "-C", "-Q", "SELECT 1"]
        interval: 5s
        timeout: 5s
        retries: 10

  migrator:
    container_name: fasttodo-migrator
    build:
        context: ../
        dockerfile: Dockerfile.Migrations
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - DB_PROJECT=${DB_PROJECT}
      - CONTEXT=${CONTEXT}
      - IDENTITY_CONNECTION_STRING=${IDENTITY_CONNECTION_STRING}
      - IDENTITY_PROJECT=${IDENTITY_PROJECT}
      - IDENTITY_CONTEXT=${IDENTITY_CONTEXT}
      - SqlProvider=${SqlProvider}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
        db:
          condition: service_healthy
    networks:
        - fasttodo-network
    restart: "no"

volumes:
  mssql_data:

networks:
  fasttodo-network:
