// <auto-generated />
using FastTodo.Persistence.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastTodo.Persistence.SQLite.Data.Todo.Migrations
{
    [DbContext(typeof(FastTodoSqliteDbContext))]
    [Migration("20250529095402_Update_TodoItem_Dates")]
    partial class Update_TodoItem_Dates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
#pragma warning restore 612, 618
        }
    }
}
