# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY ["src/FastTodo.Domain.Shared/FastTodo.Domain.Shared.csproj", "FastTodo.Domain.Shared/"]
COPY ["src/Infrastructure/FastTodo.Infrastructure.Domain.csproj", "Infrastructure/FastTodo.Infrastructure.Domain/"]
COPY ["src/FastTodo.Domain.csproj", "FastTodo.Domain/"]
COPY ["src/Persistence/FastTodo.Persistence.Postgres", "Persistence/FastTodo.Persistence.Postgres"]
COPY ["src/FastTodo.Application/FastTodo.Application.csproj", "CleanArchitecture.Application/"]
COPY ["src/FastTodo.Contracts/CleanArchitecture.Contracts.csproj", "CleanArchitecture.Contracts/"]
COPY ["src/FastTodo.Infrastructure/CleanArchitecture.Infrastructure.csproj", "CleanArchitecture.Infrastructure/"]
COPY ["src/Host/FastTodo.API.csproj", "Host/FastTodo.API/"]
RUN dotnet restore --disable-parallel "Host/FastTodo.API/Host/FastTodo.API.csproj"

# Copy the rest of the code
COPY . ../

# Build the application
RUN dotnet build ./src/Host/FastTodo.API/FastTodo.API.csproj -c Release --no-restore -o app/build

# Stage 2: Publish (Optional, but recommended)
FROM build AS publish
RUN dotnet publish ./src/Host/FastTodo.API/FastTodo.API.csproj -c Release --no-restore -o /app/publish

# Stage 3: Final (Runtime)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
ENV ASPNETCORE_HTTP_PORTS=5001
EXPOSE 5001
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FastTodo.API.dll", "--Develop"]